### PR TITLE
[BREAKING] Update node version requirement to 14+

### LINKED ISSUE #44: Replace `iltorb` npm package with `brotli` package
iltorb is no longer maintained.

Here's what ChatGPT told me about converting the usage:

~
To convert your code to use the brotli library for compression, you can make the following changes:

Update your code to import the createCompressStream function from brotli. Create a Brotli compression stream using the createCompressStream function and provide the desired compression options, such as the quality. The modified code will look like this:

```javascript
const { createCompressStream } = require('brotli');

const compressionOptions = { quality: 11 };
const compressStream = createCompressStream(compressionOptions);
```

Please note that the brotli library provides both synchronous and asynchronous compression methods. If you require asynchronous compression, you can use the createCompressStreamAsync function instead of createCompressStream.
~

### PR DESCRIPTION
**Pull request by lukemelia**
- refactored DeployPlugin to ES6 class
- update various dependencies and docs
Fixes #44

### CODE REVIEW

**Comment by lukemelia** [comment]
Also happy to help transition maintenance of this project to the ember-cli-deploy organization if that would be helpful.

**Comment by lukemelia** [comment]
Forking to release from https://github.com/ember-cli-deploy/ember-cli-deploy-compress

**Comment by cibernox** [comment]
I missed this. I believe nobody would oppose to transfer maintenance. I'll ask

**Comment by lukemelia** [comment]
Any news on this @cibernox ?

**Comment by cibernox** [comment]
I asked, seems that we're happy to transfer ownership.

**Comment by lukemelia** [comment]
Thanks. What's the next step on making this happen?

**Pull request merged**
