### PR TITLE
switch test to travis

### PR DESCRIPTION
**Pull request by sbatson5**

### CODE REVIEW

**Comment by bcardarella** [comment]
I'm :+1: on this but its not my lib

**Comment by sbatson5** [comment]
@bcardarella I think the `circle.yml` was just copied from `ember-cli-deploy`.  This app was set to run travis. Noticed the failing build on #4

**Comment by cibernox** [comment]
I also prefer travis. 
BTW, I asked Luke Melia about replacing ember-cli-deploy gzip with this addon and he seems to like the idea once it has been battle-tested on the wild a bit more.

**Comment by bcardarella** [comment]
> once it has been battle-tested on the wild a bit more

feel free to add to dy.com as a patch release to start gathering some usage 😄

**Comment by sbatson5** [comment]
Looks like my `PATH` is wrong here (copy pasta fail). I think that build is a false positive

**Comment by cibernox** [comment]
I need to investigate also if any CDN supports serving gz or br assets conditionally based on the `Accept-Encoding` http header. That would be the ideal solution for everyone, but support for that kind of rules in CDNs is not very good yet I think.

**Comment by Turbo87** [comment]
@cibernox FWIW we have the addon running for https://skylines.aero/ (aka. https://github.com/skylines-project/skylines) using https://github.com/mholt/caddy now and it seems to work very well. The default Caddy config takes care of serving the right encoding based on the `Accept-Encoding` header.

**Pull request merged**
